{% set name = "micom" %}
{% set version = "0.29.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9d93fdd5e51c429518d6f470fa4abe47127d25e1c80bebb32f0d70e68c39d02c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3
    - cobra >=0.17.1
    - jinja2 >=2.10.0
    - scikit-learn >=0.22.0
    - scipy >=1.0.0
    - python-symengine >=0.6.1
    - osqp >=0.6.2
  run:
    - python >=3
    - cobra >=0.17.1
    - jinja2 >=2.10.0
    - scikit-learn >=0.22.0
    - scipy >=1.0.0
    - python-symengine >=0.6.1
    - osqp >=0.6.2

test:
  imports:
    - micom
    - micom.data

about:
  home: https://github.com/micom-dev/micom
  license: Apache Software
  license_family: APACHE
  summary: "Microbial community modeling based on cobrapy."
