{% set name = "caper" %}
{% set version = "1.3.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bb6b2257c58482a694002df56d982a4e46cad8e4806a97c9caf8b1d9946a6e10

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyhocon >=0.3.53
    - autouri >=0.1.2.1
    - pyopenssl
    - requests
    - miniwdl
    - filelock

test:
  imports:
    - caper

about:
  home: https://github.com/ENCODE-DCC/caper
  license: MIT
  summary: Cromwell Assisted Pipeline ExecutoR
  description: Python wrapper for Cromwell

