{% set name = "protmapper" %}
{% set version = "0.0.23" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "e22ca5c5e3fac105fc1a14adc7e972c2caa36afc9d6a739061260baa9e8a7a75"

build:
  number: 0
  noarch: python
  entry_points:
    - protmapper = protmapper.cli:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
  run:
    - boto3
    - python >=3
    - rdflib
    - requests

test:
  imports:
    - protmapper
    - protmapper.rest_api
  commands:
    - protmapper --help
  requires:
    - nose

about:
  home: "https://github.com/indralab/protmapper"
  license: "BSD"
  license_family: "BSD"
  license_file: ""
  summary: "Map protein sites to human reference sequence."
  doc_url: "https://protmapper.readthedocs.io"
  dev_url: "https://github.com/indralab/protmapper"

extra:
  recipe-maintainers:
    - bgyori
