{% set version = "0.11.0" %}

package:
  name: flowsofine
  version: {{ version }}

source:
  - git_url: https://github.com/JonasKup/FlowSoFine.git
  - https://github.com/JonasKup/FlowSoFineApp.git

build:
  number: 0
  skip: False # [osx]

requirements:
  host:
    - r-base=4
    - r-essentials 
    - r-gert
    - libprotobuf
    - bioconductor-rprotobuflib
    - r-devtools
    - r-emojifont
    - r-vegan
    - bioconductor-flowcore
    - r-gridExtra
    - r-shinyjqui
    - r-shinybusy
    - r-shinyFiles
    - r-shinyjs
    - r-shinyWidgets
    - r-shinydashboard
  run:
    - r-base=4
    - r-essentials 
    - r-gert
    - libprotobuf
    - bioconductor-rprotobuflib
    - r-devtools
    - r-emojifont
    - r-vegan
    - bioconductor-flowcore
    - r-gridExtra
    - r-shinyjqui
    - r-shinybusy
    - r-shinyFiles
    - r-shinyjs
    - r-shinyWidgets
    - r-shinydashboard

test:
  commands:
    - echo "library(vegan); library(flowCore);" | R --vanilla
    - echo "library(vegan); library(flowCore); library(FlowSoFine);" | R --vanilla

about:
  home: https://github.com/JonasKup/FlowSoFine
  license: 'GPLv3+'
  #license_file: LICENSE
  summary: 'N-dimensional binning of flow cytometric data with correction for spatial dependencies.'