package:
  name: flowsofine
  version: 0.2.0

source:
  - url: https://github.com/JonasKup/FlowSoFine/archive/v0.2.0.tar.gz
    sha256: 916abba764419c53520e1603debca23d27065365f16f066df7be1e6623b98c6a
  - url: https://github.com/JonasKup/FlowSoFineApp/archive/v0.2.0.tar.gz
    sha256:: 59f1b7d25a98ffb9d01805b7956012afb6ec443a8ae20c22f2c06cf632a6d770

build:
  number: 0
  skip: False # [osx]

requirements:
  host:
    - r-base=4
    - r-essentials 
    - r-gert
    - libprotobuf
    - bioconductor-rprotobuflib
    - r-devtools
    - r-emojifont
    - r-vegan
    - bioconductor-flowcore
    - r-gridExtra
    - r-shinyjqui
    - r-shinybusy
    - r-shinyFiles
    - r-shinyjs
    - r-shinyWidgets
    - r-shinydashboard
  run:
    - r-base=4
    - r-essentials 
    - r-gert
    - libprotobuf
    - bioconductor-rprotobuflib
    - r-devtools
    - r-emojifont
    - r-vegan
    - bioconductor-flowcore
    - r-gridExtra
    - r-shinyjqui
    - r-shinybusy
    - r-shinyFiles
    - r-shinyjs
    - r-shinyWidgets
    - r-shinydashboard

test:
  commands:
    - echo "library(vegan); library(flowCore);" | R --vanilla
    - echo "library(vegan); library(flowCore); library(FlowSoFine);" | R --vanilla

about:
  home: https://github.com/JonasKup/FlowSoFine
  license: 'GPLv3+'
  #license_file: LICENSE
  summary: 'N-dimensional binning of flow cytometric data with correction for spatial dependencies.'