{% set version = "0.1.0" %}
{% set sha256 = "3a099249304e2c43e3c96ba9dfe2bb712f48e23ca62f4e3a57fa9d65a63b9e41" %}

package:
  name: flowsofine
  version: {{ version }}

source:
  git_url: https://github.com/JonasKup/FlowSoFine.git
  #git_rev: 1.1.4
  #git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 0
  #skip: False # [osx]

requirements:
  host:
    - r-base=4.0.3
    - r-devtools
    - r-plotly 
    - r-ggplot2 
    - r-dplyr
    - r-gridextra
    - r-data.table
    - r-vegan
  run:
    - r-base=4.0.3
    - r-devtools
    - r-plotly 
    - r-ggplot2 
    - r-dplyr
    - r-gridextra
    - r-data.table
    - r-vegan
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make


test:
  commands:
    - echo "library(FlowSoFine); library(flowCore); library(vegan);" | R --vanilla

about:
  home: https://github.com/JonasKup/FlowSoFine
  license: 'GPLv3+'
  #license_file: LICENSE
  summary: 'The goal of FlowSoFine is to quickly and easily generate data structures that make it easy to get statistical output starting from raw fcs-files and a metadata table.'
