{% set name = "biobambam" %}
{% set version = "2.0.144" %}
{% set datestamp = "20190927134117" %}
{% set commithash = "2526f8eae4c5017ce2ca38ee3baaf2ae" %}
{% set sha256hash = "cb60dab490a245ebdb6cd22581b428003e8a7ecde2bd4454aa7c1d4353bd08d9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/german.tischler/biobambam2/uploads/{{ commithash }}/biobambam2-{{ version }}-release-{{ datestamp }}-x86_64-linux-gnu.tar.xz
  sha256: {{ sha256hash }}

build:
  number: 0
  binary_relocation: false
  skip: True # [osx]

requirements:
  build:
  run:

test:
  commands:
    - bamsormadup --help
    - bamtofastq --help

about:
  home: https://github.com/gt1/biobambam2
  license: GPLv3
  summary: Tools for early stage alignment file processing
