{% set name = "knock-knock" %}
{% set version = "0.3.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://files.pythonhosted.org/packages/e3/18/309cec07ed664f80fcea9ea42dfd3f8c3194590bf02586749cb7b6fa64b2/knock_knock-0.3.3.tar.gz"
  sha256: "1c1c1a5c8e6554156228e3e490773ca01d8f926b7b97b67260d1a7310e16439c"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - biopython >=1.70
    - blast ==2.7.1
    - bokeh >=0.12.14
    - hits >=0.1
    - ipywidgets >=7.1.2
    - matplotlib-base >=2.1.2
    - minimap2 ==2.16
    - nbconvert >=5.3.1
    - nbformat >=4.4.0
    - numpy >=1.14.2
    - pandas >=0.22.0
    - parallel >=20190522
    - pillow >=5.0.0
    - pysam >=0.14
    - python >=3.6
    - pyyaml >=3.12
    - samtools >=1.9
    - star >=2.7.1
    - tqdm >=4.31.1

test:
  imports:
    - knock_knock
  commands:
    - knock-knock -h
    - blastn -version
    - minimap2 --version
    - samtools --version
    - STAR --version


about:
  home: "https://github.com/jeffhussmann/knock-knock"
  license: "GPL-3"
  summary: "toolkit for analyzing CRISPR knock-in experiments"

extra:
  recipe-maintainers:
    - jeffhussmann
