
{% set name = "perl-mce-shared" %}
{% set version = "1.876" %}
{% set sha256 = "2babb0115f3bc14e06d770088e792e23d7abfcbce2450e1c322d5d3046c7a48a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MARIOROY/MCE-Shared-1.876.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-socket
    - perl-constant
    - perl-storable
    - perl-mce >=1.874
    - perl-carp
    - perl-base
    - perl-time-hires
    - perl-extutils-makemaker
    - perl-test-simple
  run:
    - perl
    - perl-socket
    - perl-constant
    - perl-storable
    - perl-mce >=1.874
    - perl-carp
    - perl-base
    - perl-time-hires
    - perl-errno


test:
  imports:
    - MCE::Hobo
    - MCE::Shared
    - MCE::Shared::Array
    - MCE::Shared::Base
    - MCE::Shared::Cache
    - MCE::Shared::Condvar
    - MCE::Shared::Handle
    - MCE::Shared::Hash
    - MCE::Shared::Minidb
    - MCE::Shared::Ordhash
    - MCE::Shared::Queue
    - MCE::Shared::Scalar
    - MCE::Shared::Sequence
    - MCE::Shared::Server

about:
  home: https://github.com/marioroy/mce-shared
  license: perl_5
  summary: 'MCE extension for sharing data supporting threads and processes'

