{% set version = "3.44.3" %}
{% set name = "limma" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 46b2f59d425864dd5dd429fd2ec57fdcb508bca1e2617508b105ff4c7ac7d625
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: affy, AnnotationDbi, BiasedUrn, Biobase, ellipse, GO.db, gplots, illuminaio, locfit, MASS, org.Hs.eg.db, splines, statmod (>= 1.2.2), vsn
requirements:
  host:
    - r-base
    - libblas
    - liblapack
  run:
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Linear Models for Microarray Data'
  description: 'Data analysis, linear models and differential expression for microarray data.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  identifiers:
    - biotools:limma
  parent_recipe:
    name: bioconductor-limma
    path: recipes/bioconductor-limma
    version: 3.36.5

