{% set name = "perl-module-build-pluggable" %}
{% set version = "0.10" %}
{% set sha256 = "e5bb2acb117792c984628812acb0fec376cb970caee8ede57535e04d762b0e40" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TO/TOKUHIROM/Module-Build-Pluggable-0.10.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-test-sharedfork
    - perl-class-accessor-lite
    - perl-data-optlist
    - perl-class-method-modifiers
    - perl-file-temp
    - perl-cpan-meta
    - perl-module-load
    - perl-file-path
    - perl-module-build
    - perl-parent
    #- perl-test-more
    #- perl-file-basename

  run:
    - perl
    - perl-test-sharedfork
    - perl-class-accessor-lite
    - perl-parent
    - perl-class-method-modifiers
    - perl-file-temp
    - perl-module-load
    - perl-file-path
    - perl-module-build
    - perl-data-optlist
    #- perl-file-basename

test:
  # Perl 'use' tests
  imports:
    - Module::Build::Pluggable
    - Module::Build::Pluggable::Base
    - Module::Build::Pluggable::GithubMeta
    - Module::Build::Pluggable::Repository
    - Module::Build::Pluggable::Util

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: https://github.com/tokuhirom/Module-Build-Pluggable
  license: perl_5
  summary: 'Module::Build meets plugins'

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
