{% set name = "regenie" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rgcgithub/regenie/archive/v{{ version }}.tar.gz
  sha256: 408cfc5f277f4e9fa4ce85719193daba72c939518386c3ba65c44fd2d9bf1508
  patches:
    # Fixing postrelease issues
    # - patches/0001-use-shared-cxxopts.patch
    # - patches/0002-import-shared-Eigen3.patch
    - patches/0003-use-conda-cmakelists.patch
    # - patches/0004-fix-fail-exit-on-help.patch

build:
  number: 0


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake >=3.15
    - make
  host:
    - bgenix >=1.1.7
    - boost-cpp
    - blas=2.20=mkl
    - mkl-include
    - cxxopts
    - eigen
    - zlib
    - zstd
  run:
    - bgenix >=1.1.7
    - boost-cpp
    - blas=2.20=mkl
    - llvm-openmp
    - mkl-include
    - mkl
    - sqlite
    - zlib
    - zstd

test:
  commands:
    - test -f ${PREFIX}/bin/regenie  # [linux]
    - regenie --help

about:
  home: https://rgcgithub.github.io/regenie/
  license: MIT
  license_file: LICENSE
  summary: 'Regenie is a C++ program for whole genome regression modelling of large genome-wide association studies (GWAS).'
  dev_url: https://github.com/rgcgithub/regenie
  doc_url: https://rgcgithub.github.io/regenie/options/

extra:
  recipe-maintainers:
    - matuskosut
