{% set name = "modlamp" %}
{% set version = "4.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "8db6556c5fd6798672af5d4a26371bb9935176a44cc42ddc33a76d4fcca05017"
  patches:
    - patch

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - lxml >=3.6.4
    - matplotlib-base >=1.5.1
    - numpy >=1.10.4
    - pandas >=0.18.1
    - python
    - requests >=2.11.1
    - scikit-learn >=0.18.0
    - scipy >=0.17.0
    - joblib >=0.15.1
    - mysql-connector-python >=2.2.9

test:
  imports:
    - modlamp

about:
  home: "http://modlamp.org"
  license: "BSD"
  license_family: "BSD"
  summary: "python package for in silico peptide design and QSAR studies"
  doc_url: "https://modlamp.org/index.html"

extra:
  recipe-maintainers:
    - jaidevjoshi83
