{% set name = "imctools" %}
{% set version = "2.0.0" %}
{% set sha256  = "7fd4f9439dee711b23c425c2a630adc9747d19a88b6b54bda75835a4e365ce8d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

source:
  url: https://github.com/BodenmillerGroup/imctools/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  host:
    - python
  run:
    - python
    - numpy
    - tifffile >=0.13.5
    - scikit-image
    - scipy
    - pandas

test:
  imports:
    - imctools

about:
  home: https://github.com/BodenmillerGroup/imctools
  license: MIT
  license_file: LICENSE
  summary: An Image Mass Cytometry (IMC) file conversion tool that aims to convert IMC rawfiles (.mcd, .txt) into an intermediary ome.tiff, containing all the relevant metadata. Further it contains tools to generate simpler tiff files that can be directly be used as input files for e.g. CellProfiller, Ilastik, Fiji etc
  dev_url: https://github.com/BodenmillerGroup/imctools
  doc_url: https://github.com/BodenmillerGroup/imctools/blob/master/README.md
