{% set name = "rgcca" %}
{% set version = "3.1" %}

package:
  name: {{ name }}cmd
  version: {{ version }}

source:
  url: https://github.com/rgcca-factory/{{ name|upper }}/archive/{{ version }}.tar.gz
  sha256: 8d4ebc9011962b0e811fb9a387eae4a02d4aefb0656fc65b4211e41719950a0f

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  host:
    - wget
    - r-base
    - r-gridextra
    - r-deriv
    - r-mass
    - r-ggplot2
    - r-optparse
    - r-scales
    - r-igraph
    - r-ggrepel
    - r-openxlsx
    - r-rlang
    - r-vegan
    - r-pbapply
    - r-plotly
  run:  
    - wget
    - r-base
    - r-gridextra
    - r-deriv
    - r-mass
    - r-ggplot2
    - r-optparse
    - r-scales
    - r-igraph
    - r-ggrepel
    - r-openxlsx
    - r-rlang
    - r-vegan
    - r-pbapply
    - r-plotly

test:
  commands:
    - cd ${PREFIX} && ls && Rscript inst/launcher.R -h
    - wget https://raw.githubusercontent.com/BrainAndSpineInstitute/rgcca_ui/master/inst/extdata/agriculture.tsv && Rscript inst/launcher.R -d agriculture.tsv
    - $R -e "library('RGCCA')"

about:
  home: https://CRAN.R-project.org/package=RGCCA
  doc_url: https://github.com/BrainAndSpineInstitute/rgcca_ui#readme
  license: GPL-2.0-or-later
  license_family: GPL3
  summary: 'Multiblock data analysis concerns the analysis of several sets of variables
        (blocks) observed on the same group of individuals. The main aims of the RGCCA
        package are (i) to study the relationships between blocks and (ii) to identify
        subsets of variables of each block which are active in their relationships
        with the other blocks.'

extra:
  recipe-maintainers:
    - ecamenen
