{% set name = "refgenconf" %}
{% set version = "0.12.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "a76197f420131ed0eeaff00a6ff4631b8489b361b299d70f52ee31bf5e515e25"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pyyaml
    - requests
    - yacman >=0.8.0
    - future
    - rich >=9.0.1
    - jsonschema >=3.0.1

test:
  imports:
    - refgenconf
  requires:
    - pytest

about:
  home: "https://refgenie.databio.org"
  license: "BSD-2-Clause"
  license_family: "BSD"
  license_file: "LICENSE.txt"
  summary: "A standardized configuration object for reference genome assemblies"

extra:
  recipe-maintainers:
    - stolarczyk
