{% set version = "0.3.4" %}

package:
  name: d4binding
  version: {{ version }}

build:
  number: 0

source:
  # TODO: use formal release number when 0.3.5 is released
  url: https://github.com/38/d4-format/archive/refs/tags/v{{ version }}-2.tar.gz
  sha256: cb9558fa837df791b5f10c621ff56a4151d5d2d407fc437b22fb813ea4ff1d69 

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust >=1.30
    - gcc #[not osx]
    - clangdev
    - pkg-config
    - make
    - cmake
  run:
    - starcode
test:
  commands:
    - "true"

about:
  home: https://github.com/38/d4-format
  license: MIT
  summary: |
    The C/C++ binding for the D4 file format
extra:
  recipe-maintainers:
    - haohou
  skip-lints:
    # Because the Rust build script will build all the upstream dependencies and those dependencies contains make file that directly call gcc rather than use $(CC) variable. Thus not forcing install gcc into the environment can cause linking error as the conda system have it's own libc. 
    - should_use_compilers
