{% set version = "0.3.4" %}

package:
  name: d4binding
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://github.com/38/d4-format.git
  git_rev: 2bcd8

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - rust >=1.30
    - clangdev
    - pkg-config
    - make
    - cmake
  #host:
  run:
    - starcode
test:
  commands:
    - rbt --help

about:
  home: https://github.com/38/d4-format
  license: MIT
  summary: |
    The C/C++ binding for the D4 file format
extra:
  recipe-maintainers:
    - haohou
