{% set version = "0.1.3" %} # Remember to update sha256 below

package:
  name: abnumber
  version: '{{ version }}'

source:
  url: https://github.com/prihoda/abnumber/archive/v{{ version }}.tar.gz
  sha256: 'bdbcc31331205bf5faea4e322a98236e511ebe6511b83611c8aa1234cde69355'

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - termcolor >=1.1.0
    - anarci >=2020.04.23
  run:
    - python >=3.6
    - termcolor >=1.1.0
    - biopython
    - anarci >=2020.04.23

test:
  imports:
    - abnumber
  commands:
    - pytest test
    - papermill examples/AbNumber_getting_started.ipynb - > /dev/null
  source_files:
    - test/
    - examples/
  requires:
    - pytest
    - papermill
    - nb_conda_kernels

about:
  home: https://github.com/prihoda/AbNumber
  license: MIT
  license_family: MIT
  summary: AbNumber - Antibody numbering using ANARCI
