{% set version="2.3.2" %}
package:
  name: arvados-cwl-runner
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arvados-cwl-runner/arvados-cwl-runner-{{ version }}.tar.gz
  sha256: 3e24be11b1255b1832055293dee98bc63f53e36f49ba36b3e03db86bb503969e

build:
  noarch: python
  number: 0

requirements:
  host:
    - pip
    - python
  run:
    - python
    - ruamel.yaml >=0.15.54
    # cwltools>=3.0.20200530110633 moved cwltool.pathmapper.get_listing to cwltool.utils.get_listing
    - cwltool >=1.0.20181217162649,<3.0.20200530110633
    - schema-salad >=3.0.20181129082112
    - arvados-python-client >=1.3.1.20190301150258

test:
  imports:
    - arvados_cwl

about:
  home: https://github.com/curoverse/arvados/tree/master/sdk/cwl
  license: Apache 2.0
  summary: 'Arvados Common Workflow Language runner'
