{% set version = "1.0" %}
{% set sha256 = '4e1b3b1187eb5ab8a27133bea7039ea898b5c15b2c293fe183920921b131a004' %}


package:
  name: snptools
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/winni2k/snptools/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - openmp
    - make
  host:
    - llvm-openmp # [osx]
    - openmp
    - tabix=0.2.5
    - samtools=0.1.16
  run:
    - llvm-openmp # [osx]
    - openmp
    - tabix=0.2.5
    - samtools=0.1.16

test:
  commands:
    - bamodel
    - poprob
    - probin
    - impute
    - hapfuse
 
about:
  home: https://www.hgsc.bcm.edu/software/snptools
  license: MIT
  summary: 'SNPTools is a suite of tools that enables integrative SNP analysis in next generation sequencing data with large cohorts. It not only calls SNP in a population with high sensitivity and accuracy, but also employs a novel imputation engine to achieve highly accurate genotype calls in an efficient way.'
  maintainer: winni2k

extra:
  identifiers:
    - biotools:snptools
