{% set version = "1.0" %}
{% set sha256 = 'a36213fe6a948bde7128d4ed353ea3b398f798056ce623906a256a0281ed00d9' %}


package:
  name: snptools
  version: {{ version }}

build:
  number: 0

source:
  url: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/snptools/snptools_{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - openmp
    - make
  host:
    - llvm-openmp # [osx]
    - openmp
  run:
    - llvm-openmp # [osx]
    - openmp

test:
  commands:
    - bamodel
    - poprob
    - probin
    - impute
    - hapfuse
 
about:
  home: https://www.hgsc.bcm.edu/software/snptools
  license: MIT
  summary: 'SNPTools is a suite of tools that enables integrative SNP analysis in next generation sequencing data with large cohorts. It not only calls SNP in a population with high sensitivity and accuracy, but also employs a novel imputation engine to achieve highly accurate genotype calls in an efficient way.'

extra:
  identifiers:
    - biotools:snptools
