package:
  name: dwgsim
  version: '1.1.12'

source:
  url: https://github.com/nh13/DWGSIM/archive/dwgsim.0.1.12.tar.gz
  sha256: 230abcbc7e437dcfbb6a66a6639baa4e6d75d5186caa93fd3ee8743a824637e7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
    - ncurses
  run:
    - zlib
    - ncurses

test:
  commands:
    - printf ">a\nAAAAA" > ref.fa; dwgsim ref.fa pref

about:
  home: https://github.com/nh13/DWGSIM
  license: GNU General Public License v2 (GPLv2)
  license_family: GPL
  summary: 'Whole Genome Simulator for Next-Generation Sequencing'
