{% set name = "perl-bio-toolbox" %}
{% set version = "1.68" %}
{% set sha256 = "0063d198ebbdf16c32deb8b457501abee65a6969cde09c832e6151920ce45388" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TJ/TJPARNELL/Bio-ToolBox-1.68.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-file-which
    - perl-getopt-long
    - perl-statistics-lite
    - perl-bio-db-big
    - perl-bio-db-hts
    - perl-config-simple
    - perl-module-build
    - perl-statistics-descriptive
    - perl-module-load
    - perl-list-moreutils
    #- perl-list-util
    #- perl-test-more

  run:
    - perl
    - perl-file-which
    - perl-getopt-long
    - perl-statistics-lite
    - perl-bio-db-big
    - perl-bio-db-hts
    - perl-config-simple
    - perl-statistics-descriptive
    - perl-module-load
    - perl-list-moreutils
    #- perl-list-util

test:
  # Perl 'use' tests
  imports:
    - Bio::ToolBox
    - Bio::ToolBox::Data
    - Bio::ToolBox::Data::Feature
    - Bio::ToolBox::Data::Iterator
    - Bio::ToolBox::Data::Stream
    - Bio::ToolBox::Data::core
    - Bio::ToolBox::Data::file
    - Bio::ToolBox::GeneTools
    - Bio::ToolBox::SeqFeature
    - Bio::ToolBox::big_helper
    - Bio::ToolBox::db_helper
    - Bio::ToolBox::db_helper::alignment_callbacks
    - Bio::ToolBox::db_helper::bam
    - Bio::ToolBox::db_helper::big
    - Bio::ToolBox::db_helper::big::BedIteratorWrapper
    - Bio::ToolBox::db_helper::big::BigWigSet
    - Bio::ToolBox::db_helper::bigbed
    - Bio::ToolBox::db_helper::bigwig
    - Bio::ToolBox::db_helper::config
    - Bio::ToolBox::db_helper::constants
    - Bio::ToolBox::db_helper::hts
    - Bio::ToolBox::db_helper::seqfasta
    - Bio::ToolBox::db_helper::useq
    - Bio::ToolBox::db_helper::wiggle
    - Bio::ToolBox::parser::bed
    - Bio::ToolBox::parser::gff
    - Bio::ToolBox::parser::ucsc
    - Bio::ToolBox::parser::ucsc::builder
    - Bio::ToolBox::utility

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Bio-ToolBox
  license: perl_5
  summary: 'Tools for querying and analysis of genomic data'

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
