package:
  name: hgtools
  version: "9.0.0"

source:
  url: https://files.pythonhosted.org/packages/cb/0f/3f0f90357a51cb926593695806aaef13fdc91d9f8a6446ba0e59c6093954/hgtools-9.0.0.tar.gz
  sha256: e168baeced660af8877d8c2b452bc5ab402cd7d0fb9c613a0e394120943ac3b1

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - backports.unittest_mock

test:
  imports:
    - hgtools
    - hgtools.managers
    - hgtools.tests

about:
  home: https://github.com/jaraco/hgtools
  license: GNU General Public License (GPL)
  summary: 'Classes and setuptools plugin for Mercurial and Git repositories'
