package:
  name: hgtools
  version: "9.1.0"

source:
  url: https://files.pythonhosted.org/packages/a5/75/a28cb03c9f1c8b718b850a4a92715bf95b94b6c41e2778dc04e094d7e56e/hgtools-9.1.0.tar.gz
  sha256: 1283f8f7621c11345ac67059b68150a683017a705d2b2e67e091c5212a8419d5

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - packaging
  run:
    - python >=3.6
    - backports.unittest_mock
    - packaging

test:
  imports:
    - hgtools
    - hgtools.managers
    - hgtools.tests

about:
  home: https://github.com/jaraco/hgtools
  license: GNU General Public License (GPL)
  summary: 'Classes and setuptools plugin for Mercurial and Git repositories'
