{% set name = "perl-datetime" %}
{% set version = "1.56" %}
{% set sha256 = "5a3b5f42ee2b5ab94cbc27a76d2a3d1bbba3a867420753051577d5b74501b3a2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-1.56.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-namespace-autoclean
    - perl-test-more
    - perl-test-warnings
    - perl-try-tiny
    - perl-warnings-register
    - perl-cpan-meta-check
    - perl-test-fatal
    - perl-specio
    - perl-variable-magic
    - perl-datetime-locale
    - perl-datetime-timezone >=2.44
    - perl-params-validationcompiler >=0.26
  run:
    - perl
    - perl-namespace-autoclean
    - perl-try-tiny
    - perl-warnings-register
    - perl-cpan-meta-check
    - perl-test-fatal
    - perl-specio
    - perl-datetime-locale
    - perl-datetime-timezone >=2.44
    - perl-params-validationcompiler >=0.26

test:
  imports:
    - DateTime
    - DateTime::Duration

about:
  home: http://metacpan.org/release/DateTime
  license: artistic_2
  summary: 'A date and time object for Perl'
