{% set name = "pauvre" %}
{% set version = "0.1924" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0a5f4fab1cabf7a9dbe5ec0d21be1e2ab0fabc78c8a74453006b63677bcc038f

build:
  number: 0
  noarch: python
  entry_points:
    - pauvre=pauvre.pauvre_main:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - biopython >=1.68
    - matplotlib-base >=2.0.2
    - numpy >=1.12.1
    - pandas >=0.20.1
    - scikit-learn
    - scipy

test:
  imports:
    - pauvre
    - pauvre.lsi
    - pauvre.tests
  commands:
    - pauvre --help

about:
  home: https://github.com/conchoecia/pauvre
  license: GPL-3.0-only
  license_family: GPL3
  summary: 'Tools for plotting Oxford Nanopore and other long-read data.'
