package:
  name: fitter
  version: "1.3.0"

source:
  url: https://files.pythonhosted.org/packages/62/44/d57f7b44c015859690f6e4e6232da0abed08e5bb161959564fed07622a14/fitter-1.3.0.tar.gz
  sha256: ff0c8707c293014cee5cddaccd2a4ff4719228abdbe83462c1ceb848a1f49128

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools
    - matplotlib-base
    - numpy
    - scipy
    - pandas

  run:
    - python
    - matplotlib-base
    - numpy
    - scipy
    - pandas

test:
  imports:
    - fitter

about:
  home: http://github.com/cokelaer/fitter
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'A tool to fit data to many distributions and best one(s)'

extra:
  container:
    # matplotlib depends on libGL.so.1 from the system
    extended-base: true
