{% set name = "mhctools" %}
{% set version = "1.6.20" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6450c0b006f539246810275ce811dab364e936ecd9e06f5f1ef29e7cc9398b9c

build:
  number: 0
  entry_points:
    - mhctools = mhctools.cli.script:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - mhcflurry >=1.2.2,<1.3.0
    - mhcnames >=0.3.2
    - numpy >=1.7
    - pandas >=0.13.1
    - pip
    - pyensembl >=1.0.3
    - python
    - sercol >=0.0.2
    - six >=1.9.0
    - varcode >=0.5.9
  run:
    - mhcflurry >=1.2.2,<1.3.0
    - mhcnames >=0.3.2
    - numpy >=1.7
    - pandas >=0.13.1
    - pyensembl >=1.0.3
    - python
    - sercol >=0.0.2
    - six >=1.9.0
    - varcode >=0.5.9

test:
  imports:
    - mhctools
    - mhctools.cli
  commands:
    - mhctools --help

about:
  home: https://github.com/openvax/mhctools
  license: Apache-2.0
  license_file: LICENSE
  summary: Python interface to running command-line and web-based MHC binding predictors

extra:
  recipe-maintainers:
    - johanneskoester
    - jafors
