{% set name="womtool" %}
{% set version="74" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/broadinstitute/cromwell/archive/{{ version }}.tar.gz
  sha256: cf88b07e40087d5705605e5aed511287004c5c4f2e0002590e8ebf76b39e6364

build:
  noarch: generic
  number: 0

requirements:
  host:
    - openjdk=8
    - sbt
    - scala
  run:
    - openjdk=8
    - python

test:
  commands:
    - womtool --help

about:
  home: https://cromwell.readthedocs.io/en/develop/WOMtool/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Command line utilities for interacting with WDL"

extra:
  identifiers:
    - biotools:womtool
