{% set name="womtool" %}
{% set version="69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/broadinstitute/cromwell/archive/{{ version }}.tar.gz
  sha256: e09e0b008269b68331bd1915132e62c608b56615d31002acb36de130d8e299cc

build:
  noarch: generic
  number: 0

requirements:
  host:
    - openjdk=8
    - sbt
    - scala
  run:
    - openjdk=8
    - python

test:
  commands:
    - womtool --help

about:
  home: https://cromwell.readthedocs.io/en/develop/WOMtool/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Command line utilities for interacting with WDL"

extra:
  identifiers:
    - biotools:womtool
