{% set name="womtool" %}
{% set version="70" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/broadinstitute/cromwell/archive/{{ version }}.tar.gz
  sha256: e66df84f6d1b44b9d383c936371ce5a0f6b117dccc80653056e7495b9db7b14c

build:
  noarch: generic
  number: 0

requirements:
  host:
    - openjdk=8
    - sbt
    - scala
  run:
    - openjdk=8
    - python

test:
  commands:
    - womtool --help

about:
  home: https://cromwell.readthedocs.io/en/develop/WOMtool/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Command line utilities for interacting with WDL"

extra:
  identifiers:
    - biotools:womtool
