{% set name="womtool" %}
{% set version="67" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/broadinstitute/cromwell/archive/{{ version }}.tar.gz
  sha256: d5da414369943cc04e8f32b39c6a10047e4de27cb77a2a53d6cde0d64f74f249

build:
  noarch: generic
  number: 0

requirements:
  host:
    - openjdk=8
    - sbt
    - scala
  run:
    - openjdk=8
    - python

test:
  commands:
    - womtool --help

about:
  home: https://cromwell.readthedocs.io/en/develop/WOMtool/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: "Command line utilities for interacting with WDL"

extra:
  identifiers:
    - biotools:womtool
