{% set name = "perl-html-parser" %}
{% set version = "3.76" %}
{% set sha256 = "64d9e2eb2b420f1492da01ec0e6976363245b4be9290f03f10b7d2cb63fa2f61" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/O/OA/OALDERS/HTML-Parser-3.76.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}

  host:
    - perl
    - perl-html-tagset
    - perl-test-simple
    - perl-config 
    - perl-extutils-makemaker >=6.52
    - perl-file-spec 
    - perl-filehandle 
    - perl-io-file 
    - perl-selectsaver 
    - perl-test 
    - perl-uri 
  run:
    - perl-carp 
    - perl-exporter 
    - perl-http-headers 
    - perl-io-file 
    - perl-uri 
    - perl-uri-url
    - perl
    - perl-html-tagset

test:
  imports:
    - HTML::Filter
    - HTML::Parser

about:
  home: http://metacpan.org/pod/HTML::Parser
  license: perl_5
  summary: 'HTML parser class'
