{% set version = "1.4.2" %}

package:
  name: gatb
  version: {{ version }}

source:
  url: "https://github.com/GATB/gatb-core/archive/refs/tags/v{{ version }}.tar.gz"
  sha256: "824c84a3712973746b977a9d49923fd499021a894225231100eaad1a66e9742d"
  patches:
    - cmake_3rdparties.patch
#    - 0001-Remove-superfluous-template-keyword-in-debruijn--impl.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
    - zlib
    - hdf5
  run:
    - boost-cpp
    - zlib
    - hdf5

test:
  commands:
    - test -e ${PREFIX}/include/gatb/bank/api/Sequence.hpp

about:
  home: https://gatb.inria.fr/
  license: AGPL 3.0
  summary: The Genome Analysis Toolbox with de-Bruijn graph
