{% set name = "cazy_webscraper" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/HobnobMancer/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: daafdd47885f9f6b1f0fbda084146956f8d2ca33b6c8cf79c5d20e207581de5b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv --ignore-installed ."

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - beautifulsoup4
    - biopython
    - html5lib
    - lxml
    - mechanicalsoup
    - numpy
    - pandas
    - pyyaml
    - requests
    - sqlalchemy ==1.3.20
    - tqdm

test:
  imports:
    - scraper
  commands:
    - cazy_webscraper.py -h

about:
  home: https://hobnobmancer.github.io/cazy_webscraper/
  license: MIT
  license_file: LICENSE
  summary: 'The cazy_webscraper automates retrieval of protein data from the CAZy database.'
  license_family: MIT
