{% set version = "0.3.2" %}
{% set sha256 = "e1181b50b525ea4b17fc6a2017f148d5c07adb3a70c9e58730bb8bed17938afa" %}

package:
  name: fasten
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/lskatz/fasten/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - rust
    - {{ compiler('c') }}
  host:

test:
  commands:
    - fasten_clean --help
    - fasten_straighten --help
    - fasten_metrics --help
    - fasten_pe --help
    - fasten_randomize --help
    - fasten_combine --help
    - fasten_kmer --help
    - fasten_sample --help
    - fasten_shuffle --help
    - fasten_validate --help
    - fasten_quality_filter --help
    - fasten_trim --help
    - fasten_replace --help
    - fasten_regex --help

about:
  home: https://github.com/lskatz/fasten
  license: MIT
  license_file: LICENSE
  summary: "Perform random operations on fastq files, using unix streaming. Secure your analysis with Fasten!"
