{% set version = "1.0.5" %}
{% set name = "sparseMatrixStats" %}
{% set bioc = "3.11" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 5fac69a44fbe3d9bdbc7110536cc0c46ab3be145b5ee1c00c336d6818f214eca
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: testthat (>= 2.1.0), knitr, bench, rmarkdown, BiocStyle
# SystemRequirements: C++14
requirements:
  host:
    - 'bioconductor-matrixgenerics >=1.0.0,<1.1.0'
    - r-base
    - r-matrix
    - r-matrixstats
    - r-rcpp
    - libblas
    - liblapack
  run:
    - 'bioconductor-matrixgenerics >=1.0.0,<1.1.0'
    - r-base
    - r-matrix
    - r-matrixstats
    - r-rcpp
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Summary Statistics for Rows and Columns of Sparse Matrices'
  description: 'High performance functions for row and column operations on sparse matrices. For example: col / rowMeans2, col / rowMedians, col / rowVars etc. Currently, the optimizations are limited to data in the column sparse format. This package is inspired by the matrixStats package by Henrik Bengtsson.'
  license_file: LICENSE

