{% set name = "perl-bio-db-big" %}
{% set version = "1.0.1" %}
{% set sha256 = "8212806e2583925d3574e0afa01d5577646ed5f43115ed7f69c6c6ab17206392" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/A/AY/AYATES/Bio-DB-Big-v1.0.1.tar.gz
  sha256: {{ sha256 }}

# If this is a new build for the same version, increment the build
# number. If you do not include this key, it defaults to 0.
build:
  number: 0
  noarch: generic

requirements:
  host:
    - perl
    - perl-test-differences
    - perl-module-build
    - perl-test-output
    - perl-extutils-cbuilder
    - perl-module-build-pluggable
    - perl-test-fake-httpd
    - perl-module-build-pluggable-cpanfile
    - perl-test-exception

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Bio::DB::Big
    - Bio::DB::Big::AutoSQL
    - Bio::DB::Big::AutoSQLField
    - Bio::DB::Big::File

  # You can also put a file called run_test.pl (or run_test.py) in the recipe
  # that will be run at test time.

about:
  home: http://metacpan.org/pod/Bio-DB-Big
  license: open_source
  summary: 'Perl interface to bigWigLib for accessing the kent big formats'

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
