package:
  name: perl-owl-simple
  version: '0.51'

build:
  number: 0

requirements:
  build:
    - perl
    - perl-moose 0.89
    - perl-log-log4perl
    - perl-list-util
    - perl-xml-parser 2.34
    - perl-test-more
    - perl-file-temp
  host:
    - perl
    - perl-moose 0.89
    - perl-log-log4perl
    - perl-list-util
    - perl-xml-parser 2.34
  run:
    - perl
    - perl-moose 0.89
    - perl-log-log4perl
    - perl-list-util
    - perl-xml-parser 2.34

test:
  imports:
    - OWL::Simple::Parser
    - OWL::Simple::OBOWriter

about:
  home: https://metacpan.org/pod/OWL::Simple
  license: Perl
  summary: Perl library for OWL parsing
