{% set name = "connectome-workbench" %}
{% set version = "1.4.0" %}
{% set sha256 = "b782b913edee3386c6f0217f83369bff5ff50ac362696772dd9da4ff2b94f7d7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url:  https://github.com/Washington-University/workbench/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=2.8

  host:
    - qt >=5.7
    - libpng
    - zlib
    - openssl
    - openmp
    - freetype
    - mesa
    - libglu
    - xorg-libx11
    - xorg-libxext
    - xorg-libxfixes
    - xorg-libxcb
    - xorg-libxau
    - xorg-libxdmcp

  run:
    - qt >=5.6
    - libpng
    - zlib
    - openssl
    - openmp
    - freetype
    - mesa
    - libglu
    - xorg-libx11
    - xorg-libxext
    - xorg-libxfixes
    - xorg-libxcb
    - xorg-libxau
    - xorg-libxdmcp

test:
  commands:
    - wb_command -help
    - wb_view -help
    - wb_shortcuts -help

about:
  home: https://www.humanconnectome.org/software/connectome-workbench
  summary: "Connectome Workbench is an open source, freely available visualization and discovery tool used to map neuroimaging data, especially data generated by the Human Connectome Project"
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/Washington-University/workbench

extra:
  container:
    extended-base: True
