package:
  name: perl-xml-libxml
  version: "2.0207"

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0207.tar.gz
  sha256: 903436c9859875bef5593243aae85ced329ad0fb4b57bbf45975e32547c50c15

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-alien-build
    - perl-alien-libxml2 >=0.14
    - perl-io
    - perl-scalar-list-utils
    - perl-test-more
    - perl-utf8
    - perl-xml-sax
    - perl-xml-namespacesupport
    - libxml2
    - zlib
  run:
    - perl
    - perl-xml-sax
    - perl-xml-namespacesupport
    - libxml2
    - zlib
    - perl-carp 
    - perl-encode 
    - perl-exporter >=5.57
    - perl-io
    - perl-scalar-list-utils
    - perl-tie-hash
    - perl-xml-sax-documentlocator

test:
  imports:
    - XML::LibXML
    - XML::LibXML::AttributeHash
    - XML::LibXML::Boolean
    - XML::LibXML::Common
    - XML::LibXML::Devel
    - XML::LibXML::ErrNo
    - XML::LibXML::Error
    - XML::LibXML::Literal
    - XML::LibXML::NodeList
    - XML::LibXML::Number
    - XML::LibXML::Reader
    - XML::LibXML::SAX
    - XML::LibXML::SAX::Builder
    - XML::LibXML::SAX::Generator
    - XML::LibXML::SAX::Parser
    - XML::LibXML::XPathContext

about:
  home: https://bitbucket.org/shlomif/perl-xml-libxml
  license: Perl
  summary: 'Interface to Gnome libxml2 xml parsing and DOM library'
