{% set name = "perl-datetime-locale" %}
{% set version = "1.33" %}
{% set sha256 = "52bfefad9ff39c4d8fd1f5e78642e38b8dcd33363f337d8e89bf19e6ad185cb9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-Locale-1.33.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-cpan-meta-check
    - perl-test-requires
    - perl-test-warnings
    - perl-extutils-makemaker
    - perl-specio
    - perl-params-validationcompiler
    - perl-namespace-autoclean
    - perl-dist-checkconflicts
    - perl-file-sharedir-install >=0.06
    - perl-file-temp 
    - perl-ipc-system-simple 
    - perl-path-tiny 
    - perl-test-file-sharedir-dist 
    - perl-test-more >=1.302015
    - perl-test2-plugin-nowarnings 
    - perl-test2-plugin-utf8 
    - perl-test2-require-module 
    - perl-test2-v0 
  run:
    - perl
    - perl-namespace-autoclean
    - perl-dist-checkconflicts
    - perl-params-validationcompiler
    - perl-specio
    - perl-file-sharedir 
    - perl-pathtools
    - perl-storable 


test:
  imports:
    - DateTime::Locale
    - DateTime::Locale::Base
    - DateTime::Locale::Catalog
    - DateTime::Locale::Data
    - DateTime::Locale::FromData
    - DateTime::Locale::Util

about:
  home: http://metacpan.org/release/DateTime-Locale
  license: perl_5
  summary: 'Localization support for DateTime.pm'
