{% set name = "varcode" %}
{% set version = "0.9.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2cb3bcb5769689007b0d368cd4805feae8ae66df8beebe8da2342ac5e884ba23

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python
  entry_points:
    - varcode-genes = varcode.cli.genes_script:main
    - varcode = varcode.cli.effects_script:main

requirements:
  host:
    - biopython >=1.64
    - memoized_property >=1.0.2
    - numpy >=1.7,
    - pandas >=0.15
    - pip
    - pyensembl >=1.7.4
    - python
    - pyvcf >=0.6.7
    - sercol >=0.1.4
    - serializable >=0.1.1
  run:
    - biopython >=1.64
    - memoized_property >=1.0.2
    - numpy >=1.7,
    - pandas >=0.15
    - pyensembl >=1.7.4
    - python
    - pyvcf >=0.6.7
    - sercol >=0.1.4
    - serializable >=0.1.1

test:
  imports:
    - test
    - varcode
    - varcode.cli
    - varcode.effects
  commands:
    - varcode-genes --help
    - varcode --help

about:
  home: https://github.com/openvax/varcode
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Variant annotation in Python

extra:
  recipe-maintainers:
    - johanneskoester
