{% set name = "multiPhATE" %}
{% set version = "0.1.2" %}
{% set sha256 = "66aaf71448c044e7dc0f34d1224f7595cbd97059669a1c4cbfd9abd0853d7166" %}

package:
  name: {{ name|lower }} 
  version: 0.5 

source:
  url: https://github.com/carolzhou/multiPhATEb/archive/v{{ version }}.tar.gz
  sha256: 66aaf71448c044e7dc0f34d1224f7595cbd97059669a1c4cbfd9abd0853d7166

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
  run:
    - python
    - tRNAscan-SE
    - emboss
    - biopython
    - blast
    - glimmer
    - prodigal

test:
  commands:
    - blastp -help
    - prodigal -h
    - multiPhate.py usage

about:
  home: https://github.com/carolzhou/multiPhATEb
  license: BSD3
  license_file: BSD-3.pdf
  summary: De novo annotation of phage genome sequence.

extra:
  identifiers:
    - biotools:multiphate
    - doi:https://doi.org/10.1101/551010
