{% set version = "3.7.2" %}

package:
  name: hicexplorer
  version: '{{ version }}'

source:
  url: https://github.com/deeptools/HiCExplorer/archive/{{ version }}.tar.gz
  sha256: dca71065dd4e549d578db96870b8d650b48f3dc852918ef19a345f436f612037

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.19
    - scipy >=1.5
    - pygenometracks >=3.6
    - matplotlib-base >=3.1.*
    - ipykernel >=5.3.0
    - pysam >=0.16.*
    - intervaltree >=3.1.*
    - biopython >=1.77
    - pytables >=3.6.*
    - pybigwig >=0.3.*
    - pandas >=1.1.*
    - jinja2 >=2.11
    - cooler >=0.8.10
    - future >=0.18
    - unidecode >=1.1.*
    - hicmatrix >=15
    - cooler >=0.8.10
    - hic2cool >=0.8.3
    - fit_nbinom >=1.1
    - krbalancing >=0.0.5
    - psutil >=5.7.*
    - pybedtools >=0.8
    - hyperopt >=0.2.4
    - python-graphviz >=0.14
    - scikit-learn >=0.23.2
    - imbalanced-learn >=0.7.*
    - cleanlab >=0.1

test:
  imports:
    - hicexplorer
  commands:
    - hicFindRestSite --version
    - hicAggregateContacts --version
    - hicBuildMatrix --version
    - hicCorrectMatrix --version
    - hicCorrelate --version
    - hicDetectLoops --version
    - hicFindTADs --version
    - hicMergeMatrixBins --version
    - hicPlotMatrix --version
    - hicPlotDistVsCounts --version
    - hicPlotTADs --version
    - hicSumMatrices --version
    - hicInfo --version
    - hicConvertFormat --version
    - hicAdjustMatrix --version
    - hicNormalize --version
    - hicAverageRegions --version
    - hicPlotAverageRegions --version
    - hicMergeLoops --version
    - hicValidateLocations --version
    - hicCompartmentalization --version
    - chicQualityControl --version
    - chicViewpointBackgroundModel --version
    - chicViewpoint --version
    - chicSignificantInteractions --version
    - chicAggregateStatistic --version
    - chicDifferentialTest --version
    - chicExportData --version
    - chicPlotViewpoint --version
    - hicPlotSVL --version
    - hicQuickQC --version
    - hicCompareMatrices --version
    - hicPCA --version
    - hicTransform --version
    - hicPlotViewpoint --version
    - hicHyperoptDetectLoops --version
    - hicHyperoptDetectLoopsHiCCUPS --version
    - hicDifferentialTAD --version
    - hicInterIntraTAD --version
    - hicTADClassifier --version
    - hicTrainTADClassifier --version
    
 
about:
  home: https://github.com/deeptools/HiCExplorer
  license: GPL3
  summary: Set of programs to process, analyze and visualize Hi-C and capture Hi-C data

extra:
  identifiers:
    - doi:10.1093/nar/gky504
    - doi:10.1093/nar/gkaa220
    - usegalaxy-eu:hicexplorer_hicplotviewpoint
