{% set version = ".2.1.0" %}
{% set sha256 = "79ceb8124d5c9c810f8059e31b896b77520df13e027c58fb233b9b50a1896b0c" %}

package:
  name: metagenome-atlas
  version: {{ version }}

source:
  url: https://github.com/metagenome-atlas/atlas/archive/v{{ version }}.tar.gz 
  sha256: {{ sha256 }}

build:
  skip: True  # [osx]
  number: 0
  entry_points:
    - atlas=atlas.atlas:cli


requirements:
  build:
    - python=3.6
    - setuptools
    - snakemake>=5.4.5
    - pandas=0.23
    - click=7
    - ruamel.yaml=0.15
    - biopython>=1.70
    - git # this is apparently needed for snakemake
  run:
    - python=3.6
    - snakemake>=5.4.5
    - pandas=0.23
    - click=7
    - ruamel.yaml=0.15
    - biopython>=1.70
    - bbmap=37.78


test:
  imports:
    - atlas
  commands:
    - LANG=C.UTF-8 atlas --version
    - LANG=C.UTF-8 atlas init --help
    - LANG=C.UTF-8 atlas run --help

about:
  home: https://github.com/metagenome-atlas
  license: BSD-3-Clause
  license_family: BSD
  summary: |
    ATLAS - Three commands to start analysing your metagenome data

  description: |
    Atlas is a easy to use metagenomic pipeline
    ![scheme of workflow](https://github.com/metagenome-atlas/atlas/blob/f8627545bcfb8f2b55733a35ecd0426ae4bbd5d1/resources/images/ATLAS_scheme.png)

    # Quick Start

    Three commands to start analysing your metagenome data:
    ```
        conda install -c bioconda -c conda-forge metagenome-atlas
        atlas init --db-dir databases path/to/fastq/files
        atlas run
    ```
    All databases and dependencies are installed on the fly in the directory `db-dir`.
    You want to run these three commands on the example_data on the GitHub repo.
    If you have more time, then we recommend you configure atlas according to your needs.
      - check the `samples.tsv`
      - edit the `config.yaml`
      - run atlas on any cluster system
    For more details see documentation.

  dev_url: https://github.com/metagenome-atlas/atlas
  doc_url: https://metagenome-atlas.rtfd.io
extra:
  recipe-maintainers:
    - silask
#    - brwnj
#  identifiers:
#    - biotools:Spades
#    - doi:10.1089/cmb.2012.0021
