package:
  name: kissplice
  version: '2.5.4'

source:
  url: "ftp://pbil.univ-lyon1.fr/pub/logiciel/kissplice/download/kissplice-2.5.4.tar.gz"
  sha256: "fd234879564798445f9ff38078f9d17534a7b1b380def24e0c7fc66b6979f7b1"

build:
  number: 0
  skip: True # [osx or py3k]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - python
  run:
    - python

test:
  commands:
    - kissplice -h

about:
  home: http://kissplice.prabi.fr
  license: CeCILL license
  summary: A local transcriptome assembler for SNPs, indels and AS events
