package:
  name: kissplice
  version: '2.5.4'

source:
  url: "ftp://pbil.univ-lyon1.fr/pub/logiciel/kissplice/download/kissplice-2.5.4.tar.gz"
  sha256: "485899a0e7ccc4567a31190eedead082634ab9fa9fab8a77bab5d152ccad80ab"

build:
  number: 0
  skip: True # [osx or py3k]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - python
  run:
    - python

test:
  commands:
    - kissplice -h

about:
  home: http://kissplice.prabi.fr
  license: CeCILL license
  summary: A local transcriptome assembler for SNPs, indels and AS events
