{% set version = "1.7.1" %}
{% set sha256 = '' %}


package:
  name: glphase
  version: {{ version }}

build:
  number: 0

source:
  git_url: https://github.com/winni2k/GLPhase.git
  git_rev: v{{ version }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    - llvm-openmp # [osx]
    - openmp
    - gsl
    - zlib
    - boost
  run:
    - llvm-openmp # [osx]
    - openmp
    - gsl
    - zlib

test:
  commands:
    - glphase --help
 
about:
  home: https://github.com/winni2k/GLPhase
  license: MIT
  summary: 'A tool for phasing and imputing haplotypes in 10k+ low coverage sequencing samples'
  maintainer: winni2k

extra:
  identifiers:
    - biotools:glphase
  skip-lints: uses_git_url
