package:
  name: wheezy.template
  version: "0.1.189"

source:
  url: https://files.pythonhosted.org/packages/a5/be/b8d53b4cfdcdaa1d77d5f967bef28a29815a6036650414d34114f8b53407/wheezy.template-0.1.189.tar.gz
  sha256: 4537f758aa8d3ba2a4cb8eb28d227d15a9ad33fa050f1055fe5f54a2d648a41c

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
