package:
  name: wheezy.template
  version: "0.1.184"

source:
  url: https://files.pythonhosted.org/packages/6c/cd/3a19a8536ee71130755ee44872e485eed9586307392bac0c8a08e2fe36b5/wheezy.template-0.1.184.tar.gz
  sha256: 73d28c2cceb0f899d5e36594b49d336e2530a60997f2c10d4eaa8a26a2342ed7

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
