package:
  name: wheezy.template
  version: "3.0.2"

source:
  url: https://files.pythonhosted.org/packages/6d/88/f7780c5aaffe47026a1fa94bb652e8bc1ad37f6d9cb6ee31dc4d9a89395f/wheezy.template-3.0.2.tar.gz
  sha256: 09d3a121435f5fb0c29437c737790518e639e307739bba25116b6b0aefcf045f

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
