package:
  name: wheezy.template
  version: "0.1.192"

source:
  url: https://files.pythonhosted.org/packages/04/04/e45cbf1700671c973cbf0037dce2ad529bf87c363b5f1e08f4694f90a4e1/wheezy.template-0.1.192.tar.gz
  sha256: 29daa96c638a3b1dc2f638fcd11724efba6eda85024c4846789b970426f78202

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
