package:
  name: wheezy.template
  version: "3.0.1"

source:
  url: https://files.pythonhosted.org/packages/40/cc/e15116058981aa30d4f7b0852126c69ca92bdcdf86470e35afcab69fddd5/wheezy.template-3.0.1.tar.gz
  sha256: 8158c6821f759a424a0e4428c62104e78c37bc53d91be149072862d2764fe1e0

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
