package:
  name: wheezy.template
  version: "3.0.3"

source:
  url: https://files.pythonhosted.org/packages/89/69/d4e24356fb033d4bb19f784d983c89c7f86b6f543fcbb5cd40f83f10f1b1/wheezy.template-3.0.3.tar.gz
  sha256: 1254ba402e2f5720885945be026a643cc6820ea9b721835c9242c826c1d3e670

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
