package:
  name: wheezy.template
  version: "3.0.0"

source:
  url: https://files.pythonhosted.org/packages/f1/77/663c953a5ab1e43af843322d043a230b1d3cddb37f270fa389fb84b3dbb2/wheezy.template-3.0.0.tar.gz
  sha256: 96240be5a7382bf4accb50bf42a49c24cd8e4c2b3131d09ec7c8e743fb18ad16

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
