package:
  name: wheezy.template
  version: "0.1.195"

source:
  url: https://files.pythonhosted.org/packages/ee/f8/10736275c1df7299cacb5e10cce15a5db29b4b9f29c91fa7f8f463ed3e76/wheezy.template-0.1.195.tar.gz
  sha256: f98aa41e3d1e0c6cef935605cbbf03fb95c3652fd30294d7561dac8c8a87edf2

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
