package:
  name: wheezy.template
  version: "2.0.0"

source:
  url: https://files.pythonhosted.org/packages/7e/a2/3d1731ace8844f303c9925df2665e94f1e62ed6d663c84da867c5040bf13/wheezy.template-2.0.0.tar.gz
  sha256: 699f46b859dbf07cc250c9f9c88aa9744f1546ab622c0c464c144b09c29a0aae

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
