package:
  name: wheezy.template
  version: "0.1.193"

source:
  url: https://files.pythonhosted.org/packages/5f/af/283b4722448dca1f06d30dbc8479758865c89629cb293abb72a29cf4bbbd/wheezy.template-0.1.193.tar.gz
  sha256: f5dc9c3acfa19bef5203e2d69605e39dfb3bcbf27eef37b8e91f6e53aa9c32f4

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - wheezy
    - wheezy.template
    - wheezy.template.ext

about:
  home: https://bitbucket.org/akorn/wheezy.template
  license: MIT
  summary: 'A lightweight template library'
  license_family: MIT
