{% set version = "0.4.0" %}

package:
  name: mintie
  version: {{ version }}

source:
  url: https://github.com/Oshlack/MINTIE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d58d14cd053b90e1ee90af1599a4a7e7ffb7e690c8f87947ab3e514850342d8d

build:
  number: 0
  noarch: generic

requirements:
  run:
    - bpipe
    - fastuniq
    - trimmomatic
    - soapdenovo-trans=1.03
    - fastx_toolkit
    - bbmap
    - samtools
    - bedtools
    - gmap>=2021.06.04
    - tbb=2020.2
    - salmon
    - python
    - numpy
    - pandas
    - pysam
    - pybedtools
    - biopython
    - intervaltree_bio
    - r-base
    - r-dplyr
    - r-data.table
    - r-readr
    - r-jsonlite
    - r-statmod
    - bioconductor-tximport
    - bioconductor-edger

test:
  commands:
    - mintie -h
    - cd /tmp && bpipe --help

about:
  home: https://github.com/Oshlack/MINTIE
  license: MIT
  summary: |
    Method for Identifying Novel Transcripts and Isoforms
    using Equivalence classes, in cancer and rare disease.

extra:
  recipe-maintainers:
    - mcmero
