package:
    name: salmon
    version: 0.6.0

build:
  number: 4
  # XXX OSX currently failing due to problem with bundled shared libraries
  skip: True  # [osx]

source:
  url: https://github.com/COMBINE-lab/salmon/releases/download/v0.6.0/SalmonBeta-0.6.0_OSX_10.11.tar.gz # [osx]
  url: https://github.com/COMBINE-lab/salmon/archive/v0.6.0.tar.gz # [linux]

requirements:
  build:
    - boost {{CONDA_BOOST}}*
    - cmake
    - tbb 2020.2
  run:
    - boost {{CONDA_BOOST}}*
    - tbb 2020.2

test:
    commands:
      - salmon --help


about:
    home: https://github.com/COMBINE-lab/salmon
    license: GPLv3
    summary: Highly-accurate & wicked fast transcript-level quantification from RNA-seq reads using lightweight alignments
