{% set version="0.7.0" %}

package:
  name: genefuse
  version: {{ version }}

source:
  url: https://github.com/OpenGene/GeneFuse/archive/v{{ version }}.tar.gz
  sha256: 0b29bf664c8bc34662f19228cd6fb19e20324f341b01361e4f08b029a846e59f
  patches:
    - patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - genefuse --help

about:
  home: https://github.com/OpenGene/genefuse
  license: MIT
  summary: Gene fusion detection and visualization
