{% set version = "0.3.4" %}

package:
  name: d4tools
  version: {{ version }}

build:
  number: 0

source:
  # TODO: use formal release number when 0.3.5 is released
  url: https://github.com/38/d4-format/archive/refs/tags/v{{ version }}-1.tar.gz
  sha256: c65bce345b67dc4f7f8f72d1d910d20db8a552d2b333956355eadc23b54e3fec

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - gcc
    - rust >=1.30
    - clangdev
    - pkg-config
    - make
    - cmake
  run:
    - starcode

test:
  commands:
    - rbt --help

about:
  home: https://github.com/38/d4-format
  license: MIT
  summary: |
    The D4 command line utility program
extra:
  recipe-maintainers:
    - haohou
